ervices:
- name: telegram-pdf-bot
  env:
    - key: FLASK_APP
      value: app.py
    - key: FLASK_ENV
      value: production
    - key: TELEGRAM_BOT_TOKEN
      value: '6259718751:AAEjFAu83hn_tDDZS8-8kG5nMgDzR1vhviA'
  github:
    branch: main
